/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'site-settings': SiteSetting;
    'workflow-phases': WorkflowPhase;
    'use-cases': UseCase;
    'gap-analyses': GapAnalysis;
    'schema-templates': SchemaTemplate;
    documents: Document;
    policies: Policy;
    audits: Audit;
    clauses: Clause;
    comparisons: Comparison;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'workflow-phases': WorkflowPhasesSelect<false> | WorkflowPhasesSelect<true>;
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    'gap-analyses': GapAnalysesSelect<false> | GapAnalysesSelect<true>;
    'schema-templates': SchemaTemplatesSelect<false> | SchemaTemplatesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    audits: AuditsSelect<false> | AuditsSelect<true>;
    clauses: ClausesSelect<false> | ClausesSelect<true>;
    comparisons: ComparisonsSelect<false> | ComparisonsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  title: string;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  landingSections?:
    | {
        sectionId: 'integrations' | 'docs' | 'pricing';
        title: string;
        summary: string;
        ctaLabel: string;
        ctaHref: string;
        items?:
          | {
              label: string;
              detail: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-phases".
 */
export interface WorkflowPhase {
  id: number;
  index: string;
  label: string;
  summary: string;
  href: string;
  kicker: string;
  title: string;
  description: string;
  artifact: string;
  checks?:
    | {
        check: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: string;
  title: string;
  audience: string;
  priority: 'High' | 'Medium' | 'Low';
  status: 'Defined' | 'In Progress' | 'Draft';
  slug: string;
  details: string;
  gap: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gap-analyses".
 */
export interface GapAnalysis {
  id: number;
  area: string;
  status: string;
  details: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schema-templates".
 */
export interface SchemaTemplate {
  id: number;
  slug: string;
  label: string;
  endpoint: string;
  ownership: string;
  workflow: string;
  fields?:
    | {
        name: string;
        fieldType:
          | 'text'
          | 'textarea'
          | 'richText'
          | 'select'
          | 'date'
          | 'group'
          | 'array'
          | 'relationship'
          | 'checkbox';
        required: boolean;
        note: string;
        id?: string | null;
      }[]
    | null;
  relationships?:
    | {
        relation: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  status: 'Draft' | 'Legal review' | 'Signed off';
  owner: number | User;
  sourceFile: number | Media;
  sections?:
    | {
        text: string;
        notes: string;
        id?: string | null;
      }[]
    | null;
  signoff?: {
    approver?: (number | null) | User;
    timestamp?: string | null;
    disposition?: ('approved' | 'rejected') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  status: 'Proposed' | 'Compliance review' | 'Active';
  owner: number | User;
  jurisdiction: string;
  effectiveDate: string;
  exceptions?:
    | {
        rationale: string;
        owner?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audits".
 */
export interface Audit {
  id: number;
  title: string;
  status: 'Queued' | 'Checked' | 'Remediation';
  owner: number | User;
  scope: string;
  checks?:
    | {
        name: string;
        passed: boolean;
        evidence?: string | null;
        id?: string | null;
      }[]
    | null;
  requiresRemediation?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses".
 */
export interface Clause {
  id: number;
  title: string;
  status: 'Extracted' | 'Classified' | 'Reusable';
  owner: number | User;
  clauseText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  clauseType: 'Indemnity' | 'Liability' | 'Termination' | 'IP' | 'Governing Law' | 'Other';
  sourceLocation?: {
    document?: (number | null) | Document;
    page?: string | null;
    section?: string | null;
    confidence?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons".
 */
export interface Comparison {
  id: number;
  title: string;
  status: 'Selected' | 'Compared' | 'Resolved';
  owner: number | User;
  baselineDocument: number | Document;
  candidateDocument: number | Document;
  deltas?:
    | {
        type: 'addition' | 'removal' | 'modification';
        clause?: (number | null) | Clause;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'workflow-phases';
        value: number | WorkflowPhase;
      } | null)
    | ({
        relationTo: 'use-cases';
        value: string | UseCase;
      } | null)
    | ({
        relationTo: 'gap-analyses';
        value: number | GapAnalysis;
      } | null)
    | ({
        relationTo: 'schema-templates';
        value: number | SchemaTemplate;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'audits';
        value: number | Audit;
      } | null)
    | ({
        relationTo: 'clauses';
        value: number | Clause;
      } | null)
    | ({
        relationTo: 'comparisons';
        value: number | Comparison;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  landingSections?:
    | T
    | {
        sectionId?: T;
        title?: T;
        summary?: T;
        ctaLabel?: T;
        ctaHref?: T;
        items?:
          | T
          | {
              label?: T;
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-phases_select".
 */
export interface WorkflowPhasesSelect<T extends boolean = true> {
  index?: T;
  label?: T;
  summary?: T;
  href?: T;
  kicker?: T;
  title?: T;
  description?: T;
  artifact?: T;
  checks?:
    | T
    | {
        check?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  audience?: T;
  priority?: T;
  status?: T;
  slug?: T;
  details?: T;
  gap?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gap-analyses_select".
 */
export interface GapAnalysesSelect<T extends boolean = true> {
  area?: T;
  status?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schema-templates_select".
 */
export interface SchemaTemplatesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  endpoint?: T;
  ownership?: T;
  workflow?: T;
  fields?:
    | T
    | {
        name?: T;
        fieldType?: T;
        required?: T;
        note?: T;
        id?: T;
      };
  relationships?:
    | T
    | {
        relation?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  sourceFile?: T;
  sections?:
    | T
    | {
        text?: T;
        notes?: T;
        id?: T;
      };
  signoff?:
    | T
    | {
        approver?: T;
        timestamp?: T;
        disposition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  jurisdiction?: T;
  effectiveDate?: T;
  exceptions?:
    | T
    | {
        rationale?: T;
        owner?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audits_select".
 */
export interface AuditsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  scope?: T;
  checks?:
    | T
    | {
        name?: T;
        passed?: T;
        evidence?: T;
        id?: T;
      };
  requiresRemediation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses_select".
 */
export interface ClausesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  clauseText?: T;
  clauseType?: T;
  sourceLocation?:
    | T
    | {
        document?: T;
        page?: T;
        section?: T;
        confidence?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons_select".
 */
export interface ComparisonsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  owner?: T;
  baselineDocument?: T;
  candidateDocument?: T;
  deltas?:
    | T
    | {
        type?: T;
        clause?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}